### PR TITLE
add ci script for inference

### PR DESCRIPTION
**Pull request by LianxinGao**
as title

### CODE REVIEW

**Review by mikecovlee — CHANGES_REQUESTED** [review]
CI still failing

**Comment by LianxinGao** [comment]
> CI still failing

fixed.

**Review by yezhem — CHANGES_REQUESTED** [review]
run_on_gpu only test the main branch, can you add new action to checkout the current pr branch ?

**Comment by merlintang** [comment]
do we need to add the chatglm test into the workflow?

**Comment by LianxinGao** [comment]
> run_on_gpu only test the main branch, can you add new action to checkout the current pr branch ?

got you

**Pull request closed without merging**
