### PR TITLE
add colab example

### PR DESCRIPTION
**Pull request by LianxinGao**
as title

### CODE REVIEW

**Review by mikecovlee — CHANGES_REQUESTED** [review]
Plz use markdown URL instead.
```
[Google Colab](https://colab.research.google.com/drive/13ABrrcOv5iG1TCdKGZvxy9QN6YwPpOoI?usp=sharing)
```

**Comment by LianxinGao** [comment]
> Plz use markdown URL instead.
> 
> ```
> [Google Colab](https://colab.research.google.com/drive/13ABrrcOv5iG1TCdKGZvxy9QN6YwPpOoI?usp=sharing)
> ```

got

**Comment by mikecovlee** [comment]
Plz re-request review when you are finished.

**Review by mikecovlee — APPROVED** [review]
LGTM

**Pull request merged**
